### ISSUE TITLE
rake about

### ISSUE THREAD

**Issue by linkalis** [railsmn/project-schedule-old-obsolete#1]
Did "rake about" before changing username and encoding, and got error "FATAL:  Peer authentication failed for user "open_camp" "

**Comment by arippberger** [comment]
I'm receiving the same error. Were you able to work past this?

**Comment by derekrockwell** [comment]
Terribly sorry about the delay -- but better is late than never, I hope!

When you run 'rake about' it is actually loading all of our Ruby on Rails environment, including our database configuration. The error is indicating that it was unable to connect to the 'open_camp' database, because it doesn't exist. Our VM is set up to connect to the 'vagrant' database and we have some directions to do so in the session1 writeup.

**Comment by derekrockwell** [comment]
Marking this as closed, thanks for the note! :+1:
